const SERVER_ERROR = 500;
const VALIDATION_ERROR = 400;
const NOT_FOUND = 404;

const FORBIDDEN = 403;
const CONFLICT = 409;
const UNAUTHORIZED = 401;

module.exports = {
  SERVER_ERROR,
  VALIDATION_ERROR,
  NOT_FOUND,
  FORBIDDEN,
  CONFLICT,
  UNAUTHORIZED,
};
